# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tokken', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_managment.User')),
            ],
        ),
    ]
