# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0002_usertokken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokken',
            name='user_tokken',
            field=models.CharField(max_length=30),
        ),
    ]
