# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0003_auto_20171105_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_managment.User'),
        ),
    ]
