# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0004_auto_20171105_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestoreCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_managment.User')),
            ],
        ),
    ]
