# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_promocodes'),
        ('account_managment', '0006_auto_20171107_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_managment.User')),
            ],
        ),
    ]
