# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0007_userservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservices',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2017, 11, 16, 18, 12, 15, 858851, tzinfo=utc), verbose_name='end time'),
            preserve_default=False,
        ),
    ]
