# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0008_userservices_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservices',
            name='id',
        ),
        migrations.AlterField(
            model_name='userservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.Services'),
        ),
    ]
