# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0009_auto_20171116_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.PositiveIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
