# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(max_length=20)),
            ],
        ),
    ]
