# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
