# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_promocodes_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodes',
            name='id',
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='promo_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
