# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20171116_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.AddField(
            model_name='servicescosts',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services'),
        ),
    ]
